### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by zyfjfj** [suyuan32/simple-admin-core#5]
能否把源代码运行写的详细一些，谢谢

**Comment by suyuan32** [comment]
https://suyuan32.github.io/simple-admin-core/#/simple-admin/zh-cn/docs/env_setting

**Comment by zyfjfj** [comment]
报一下错误是什么原因？
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x1296fbd]
goroutine 1 [running]:
github.com/suyuan32/simple-admin-tools/plugins/registry/consul.LoadYAMLConf(0x0?, {0x2b26203?, 0xc00018e1e0?}, {0x28878a0, 0xc000184000})
        C:/Users/zyfjf/go/pkg/mod/github.com/suyuan32/simple-admin-tools/plugins/registry/consul@v0.0.0-20220923060146-bde681863b8d/config.go:58 +0x3d
main.main()
        D:/learn/simple-admin-core/api/core.go:51 +0x156
exit status 2
```

**Comment by suyuan32** [comment]
https://suyuan32.github.io/simple-admin-core/#/simple-admin/zh-cn/docs/consul

**Comment by suyuan32** [comment]
https://suyuan32.github.io/simple-admin-core/#/simple-admin/zh-cn/docs/deploy_docker

**Comment by suyuan32** [comment]
或者docker 内运行
